-- ============================================
-- Bot稼働監視テーブル
-- Supabase SQL Editor で実行してください
-- ============================================

create table if not exists public.bot_runs (
  id          bigint generated by default as identity primary key,
  ran_at      timestamptz not null default now(),
  status      text not null default 'success',   -- success / error
  items_found    integer not null default 0,
  items_inserted integer not null default 0,
  message     text
);

-- 新しい順で取得するためのインデックス
create index if not exists idx_bot_runs_ran_at on public.bot_runs (ran_at desc);

-- フロント（anonキー）から閲覧できるように
grant select on public.bot_runs to anon;

-- bot（service_roleキー）は自動で全権限を持つので追加不要
-- RLSを有効化する場合は以下も実行：
-- alter table public.bot_runs enable row level security;
-- create policy "anon read bot_runs" on public.bot_runs for select to anon using (true);
