-- ============================================
-- NeageWatch v3 マイグレーション
-- Supabase SQL Editor で実行してください
-- ============================================

-- price_changes に内容量・報告数カラムを追加
alter table public.price_changes
  add column if not exists amount         text,      -- 内容量（例: "60g", "1デーパスポート"）
  add column if not exists report_count   integer default 0,  -- ユーザーからの誤り報告数
  add column if not exists is_verified    boolean default false; -- 手動検証済みフラグ（seedデータ等）

-- 既存の change_date / article_date を null許容に（情報がなければ NULL にするため）
alter table public.price_changes
  alter column change_date  drop not null,
  alter column article_date drop not null;

-- ============================================
-- 情報修正レポート用テーブル（問い合わせボタン）
-- ============================================
create table if not exists public.reports (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  price_change_id bigint references public.price_changes(id) on delete cascade,
  report_type text not null,        -- 'wrong_price' / 'wrong_date' / 'wrong_amount' / 'other'
  detail      text,                 -- ユーザーの補足
  status      text default 'open'   -- 'open' / 'resolved'
);

create index if not exists idx_reports_status on public.reports (status, created_at desc);

-- anonからの投稿を許可（RLSを使う場合）
grant insert on public.reports to anon;
grant usage on sequence public.reports_id_seq to anon;
grant select on public.price_changes to anon;
