(()=>{
const kyoto=window.KYOTO_CHANNELS||[];
const national=window.NATIONAL_CHANNELS||[];
const all=[...kyoto,...national];
const $=id=>document.getElementById(id);
const E={prev:$('prev'),next:$('next'),mapBtn:$('mapBtn'),yearAgo:$('yearAgo'),scheduleBtn:$('scheduleBtn'),random:$('random'),auto:$('auto'),guideBtn:$('guideBtn'),liveOnly:$('liveOnly'),compareTop:$('compareTop'),layout:$('layout'),guide:$('guide'),search:$('search'),tabs:$('tabs'),regions:$('regions'),seasons:$('seasons'),channels:$('channels'),upnext:$('upnext'),chapters:$('chapters'),history:$('history'),clock:$('clock'),boot:$('boot'),start:$('start'),zap:$('zap'),zapNum:$('zapNum'),zapName:$('zapName'),bugNum:$('bugNum'),bugName:$('bugName'),liveMark:$('liveMark'),title:$('title'),meta:$('meta'),channelStat:$('channelStat'),stage:$('stage'),compareList:$('compareList'),compareHint:$('compareHint'),regionSwitch:$('regionSwitch'),brandSub:$('brandSub'),guideTitle:$('guideTitle'),programBadge:$('programBadge'),daypartLabel:$('daypartLabel'),scheduleList:$('scheduleList'),mapModal:$('mapModal'),mapClose:$('mapClose'),mapTitle:$('mapTitle')};
let region='京都',data=[],current=0,cat='すべて',area='すべて',season='すべて',started=false,apiReady=false,autoNext=true,scheduleMode=true,activeSlot=0,slotMap=[0,1,0],map=null,mapLayer=null,annivCursor=0,lastSchedule='';
let favs=JSON.parse(localStorage.getItem('jttv-favs')||'[]');
let history=JSON.parse(localStorage.getItem('jttv-history')||'[]');
const slots=[...document.querySelectorAll('.slot')],players=[null,null,null];
const regionOrder=['京都','東京','大阪','奈良','北海道','沖縄','全国'];
const catOrder=['すべて','LIVE','1年前','王道名所','街歩き','スポット直行','夜の京都','夜の街','自然・散策','季節','グルメ','癒やし','★お気に入り'];
const seasonOrder=['すべて','今','春','夏','秋','冬','通年'];
const key=v=>`${v.region||'京都'}:${v.num}`;
const save=()=>{localStorage.setItem('jttv-favs',JSON.stringify(favs));localStorage.setItem('jttv-history',JSON.stringify(history))};
function toast(t){const x=$('toast');if(!x)return;x.textContent=t;x.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>x.classList.remove('show'),1300)}
function nowJST(){return new Date(new Date().toLocaleString('en-US',{timeZone:'Asia/Tokyo'}))}
function hhmm(d){return `${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function regionData(r){return r==='全国'?all:all.filter(v=>(v.region||'京都')===r)}
function seasonOf(v){if(v.live)return'今';if(v.season)return v.season;const t=`${v.name} ${v.title} ${v.meta}`;if(/桜|春/.test(t))return'春';if(/新緑|夏|川床|お盆/.test(t))return'夏';if(/秋|紅葉/.test(t))return'秋';if(/雪|冬/.test(t))return'冬';return'通年'}
function daypart(){const h=nowJST().getHours();if(h>=5&&h<10)return{name:'朝',cats:['LIVE','癒やし','自然・散策','王道名所']};if(h>=10&&h<17)return{name:'昼',cats:['王道名所','街歩き','グルメ','自然・散策','スポット直行']};if(h>=17&&h<21)return{name:'夕方',cats:['街歩き','夜の京都','夜の街','グルメ','LIVE']};return{name:'夜',cats:['夜の京都','夜の街','癒やし','LIVE','季節']}}
function isFav(v){return favs.includes(key(v))}
function toggleFav(v){const k=key(v);favs=isFav(v)?favs.filter(x=>x!==k):[...favs,k];save();renderChannels();toast(isFav(v)?'お気に入りに追加':'お気に入りから削除')}
function renderRegionSwitch(){E.regionSwitch.innerHTML='';regionOrder.forEach(r=>{if(r!=='全国'&&!all.some(v=>(v.region||'京都')===r))return;const b=document.createElement('button');b.className='regionBtn'+(r===region?' active':'');b.textContent=r;b.onclick=()=>setRegion(r);E.regionSwitch.appendChild(b)})}
function cats(){const p=new Set(data.map(v=>v.cat));return catOrder.filter(c=>c==='すべて'||c==='★お気に入り'||p.has(c)||(c==='LIVE'&&data.some(v=>v.live)))}
function areas(){return['すべて',...new Set(data.map(v=>v.area).filter(Boolean))]}
function tabs(box,list,type){box.innerHTML='';list.forEach(v=>{const state=type==='cat'?cat:type==='area'?area:season;const b=document.createElement('button');b.className=(type==='season'?'season':'tab')+(state===v?' active':'');b.textContent=v;b.onclick=()=>{if(type==='cat')cat=v;else if(type==='area')area=v;else season=v;tabs(box,list,type);renderChannels()};box.appendChild(b)})}
function matches(v,q){if(cat==='★お気に入り'&&!isFav(v))return false;if(cat!=='すべて'&&cat!=='★お気に入り'){if(cat==='LIVE'&&!v.live)return false;else if(cat!=='LIVE'&&v.cat!==cat)return false}if(area!=='すべて'&&v.area!==area)return false;if(season!=='すべて'&&seasonOf(v)!==season)return false;if(q&&!`${v.name} ${v.title} ${v.meta} ${v.cat} ${v.area} ${v.region}`.toLowerCase().includes(q))return false;return true}
function renderChannels(){const q=(E.search.value||'').toLowerCase().trim();let list=data.map((v,i)=>({v,i})).filter(x=>matches(x.v,q));if(scheduleMode){const d=daypart();list.sort((a,b)=>Number(d.cats.includes(b.v.cat)||b.v.live)-Number(d.cats.includes(a.v.cat)||a.v.live))}E.channels.innerHTML='';list.forEach(({v,i})=>{const row=document.createElement('div');row.className='ch'+(i===current?' active':'');row.setAttribute('role','button');row.setAttribute('tabindex','0');const badge=v.live?'<span class="liveBadge">LIVE</span>':v.cat==='1年前'?'<span class="annivBadge">1年前</span>':v.cat==='スポット直行'?'<span class="directBadge">直行</span>':'';row.innerHTML=`<span class="num">${v.num}</span><span class="thumbWrap"><img class="thumb" src="https://i.ytimg.com/vi/${v.id}/mqdefault.jpg" alt="">${badge}</span><span class="txt"><span class="ct">${v.name}</span><span class="cm">${v.area||''} ・ ${v.title}</span></span><button type="button" class="fav" aria-label="お気に入り">${isFav(v)?'★':'☆'}</button>`;row.onclick=e=>{if(!e.target.closest('.fav'))switchTo(i,true,true)};row.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();switchTo(i,true,true)}};row.querySelector('.fav').onclick=e=>{e.stopPropagation();toggleFav(v)};E.channels.appendChild(row)})}
function nearby(v){return all.filter(x=>key(x)!==key(v)&&(x.region||'京都')===(v.region||'京都')&&((x.area&&x.area===v.area)||(x.lat&&v.lat&&Math.abs(x.lat-v.lat)<.012&&Math.abs(x.lng-v.lng)<.018)))}
function renderCompare(){E.compareList.innerHTML='';const v=data[current],rel=nearby(v).sort((a,b)=>Number(!!b.live)-Number(!!a.live));rel.slice(0,6).forEach(x=>{const b=document.createElement('button');b.className='compareBtn'+(x.live?' live':'');b.textContent=(x.live?'🔴 ':'')+x.name+(x.live?'':` ・ ${seasonOf(x)}`);b.onclick=()=>tuneGlobal(x);E.compareList.appendChild(b)});E.compareHint.textContent=rel.length?'同じ場所のLIVE・季節・別アングルを比較できます。':'比較候補を準備中です。'}
function schedulePool(){const d=daypart();const p=data.filter(v=>v.live||d.cats.includes(v.cat));return p.length?p:data}
function scheduled(offset=0){const p=schedulePool();if(!p.length)return null;const n=nowJST(),slot=Math.floor((n.getHours()*60+n.getMinutes())/30)+offset;return p[((slot%p.length)+p.length)%p.length]}
function renderSchedule(){const d=daypart();E.daypartLabel.textContent=`日本時間 ${d.name}`;E.scheduleList.innerHTML='';for(let k=0;k<4;k++){const v=scheduled(k);if(!v)continue;const n=nowJST();n.setMinutes(Math.floor(n.getMinutes()/30)*30+k*30,0,0);E.scheduleList.innerHTML+=`<div class="mi"><span class="mn">${hhmm(n)}</span><span class="mt">${v.region||'京都'}・${v.name}</span></div>`}E.programBadge.textContent=scheduleMode?`🕒 自動編成：${d.name}`:''}
function renderSide(){if(!data.length)return;E.upnext.innerHTML='';const base=nowJST();base.setMinutes(Math.floor(base.getMinutes()/30)*30,0,0);for(let k=0;k<4;k++){const v=data[(current+k)%data.length],t=new Date(base.getTime()+k*1800000);E.upnext.innerHTML+=`<div class="mi"><span class="mn">${v.live?'LIVE':hhmm(t)}</span><span class="mt">${v.num} ${v.name}</span></div>`}E.history.innerHTML='';history.slice(0,4).forEach(k=>{const v=all.find(x=>key(x)===k);if(v)E.history.innerHTML+=`<div class="mi"><span class="mn">${v.num}</span><span class="mt">${v.region||'京都'}・${v.name}</span></div>`});if(!history.length)E.history.innerHTML='<div class="compareHint">まだ履歴はありません</div>';E.chapters.innerHTML='';const v=data[current];if(v.live)E.chapters.innerHTML='<span class="compareHint">LIVE配信中です。</span>';else if(v.chapters){v.chapters.forEach(([label,sec])=>{const b=document.createElement('button');b.className='chapter';b.textContent=label;b.onclick=()=>{const p=players[activeSlot];if(p&&p.seekTo){p.seekTo(sec,true);p.playVideo()}};E.chapters.appendChild(b)})}else if(v.start!=null)E.chapters.innerHTML='<span class="compareHint">該当スポットの時刻から直接再生します。</span>';else E.chapters.innerHTML='<span class="compareHint">スポットジャンプ未登録</span>';renderCompare();renderSchedule()}
function videoSpec(v){return{videoId:v.id,startSeconds:v.start||0}}
function findSlot(i){return slotMap.findIndex(x=>x===i)}
function cue(slot,i,play=false){slotMap[slot]=i;if(!apiReady||!players[slot]||!data[i])return;try{play?players[slot].loadVideoById(videoSpec(data[i])):players[slot].cueVideoById(videoSpec(data[i]))}catch(e){}}
function resetPool(){if(!data.length)return;slotMap=[0,Math.min(1,data.length-1),data.length-1];activeSlot=0;slots.forEach((s,i)=>s.classList.toggle('active',i===0));if(apiReady)for(let s=0;s<3;s++)cue(s,slotMap[s],false)}
function switchTo(i,user=false,play=false){if(!data.length)return;i=(i+data.length)%data.length;const old=activeSlot;let target=findSlot(i);if(target<0){target=[0,1,2].find(s=>s!==activeSlot);cue(target,i,false)}current=i;activeSlot=target;const v=data[i];E.zapNum.textContent=v.num;E.zapName.textContent=v.name;E.zap.classList.add('show');if(started&&apiReady&&players[old]&&old!==activeSlot)try{players[old].pauseVideo()}catch(e){}setTimeout(()=>{slots.forEach((s,n)=>s.classList.toggle('active',n===activeSlot));E.zap.classList.remove('show');if(started&&play&&apiReady&&players[activeSlot])try{players[activeSlot].playVideo()}catch(e){}},90);E.bugNum.textContent=v.num;E.bugName.textContent=v.name;E.liveMark.classList.toggle('show',!!v.live);E.title.textContent=v.title;E.meta.textContent=`${v.region||'京都'} ・ ${v.area||''} ・ ${v.meta||''} ・ ${v.cat||''}`;if(user){const k=key(v);history=[k,...history.filter(x=>x!==k)].slice(0,10);save()}renderChannels();renderSide()}
function setRegion(r){region=r;data=regionData(r);current=0;cat='すべて';area='すべて';season='すべて';E.search.value='';renderRegionSwitch();E.brandSub.textContent=r==='全国'?'全国を旅するテレビ':`${r}を旅するテレビ`;E.guideTitle.textContent=r==='全国'?'全国チャンネル':`${r}チャンネル`;E.channelStat.textContent=`${data.length} CH ・ LIVE ${data.filter(v=>v.live).length}`;tabs(E.regions,areas(),'area');tabs(E.tabs,cats(),'cat');tabs(E.seasons,seasonOrder,'season');resetPool();switchTo(0,false,false);if(scheduleMode)applySchedule(true);renderMapMarkers();toast(`${r}へ切替`)}
function tuneGlobal(v){if(!v)return;const r=v.region||'京都';if(region!=='全国'&&region!==r)setRegion(r);const i=data.findIndex(x=>key(x)===key(v));if(i>=0)switchTo(i,true,true)}
function applySchedule(force=false){if(!scheduleMode||!data.length)return;const n=nowJST(),token=`${region}-${n.getFullYear()}-${n.getMonth()}-${n.getDate()}-${n.getHours()}-${Math.floor(n.getMinutes()/30)}`;if(!force&&token===lastSchedule)return;lastSchedule=token;const v=scheduled(0);if(v){const i=data.findIndex(x=>key(x)===key(v));if(i>=0)switchTo(i,false,started)}}
function jumpYearAgo(){const n=nowJST(),target=new Date(n.getFullYear()-1,n.getMonth(),n.getDate());let c=data.filter(v=>v.filmed).map(v=>({v,d:Math.abs(new Date(v.filmed+'T12:00:00')-target)/86400000})).filter(x=>x.d<=31).sort((a,b)=>a.d-b.d);if(!c.length)return toast('前年同時期映像は準備中');const x=c[annivCursor++%c.length];tuneGlobal(x.v);toast(`${x.v.filmed} の映像`)}
function renderMapMarkers(){if(!map||!mapLayer||!window.L)return;mapLayer.clearLayers();const seen=new Set(),bounds=[];data.filter(v=>v.lat!=null&&v.lng!=null).forEach(v=>{const sig=`${v.region}-${Number(v.lat).toFixed(3)}-${Number(v.lng).toFixed(3)}-${v.area}`;if(seen.has(sig))return;seen.add(sig);const node=document.createElement('div');node.innerHTML=`<b>${v.region||'京都'}・${v.name}</b><div style="font-size:11px;margin-top:3px">${v.area||''} / ${v.live?'LIVE':v.cat}</div>`;const b=document.createElement('button');b.className='mapTune';b.textContent='このCHを見る';b.onclick=()=>{tuneGlobal(v);closeMap()};node.appendChild(b);L.marker([v.lat,v.lng]).bindPopup(node).addTo(mapLayer);bounds.push([v.lat,v.lng])});if(bounds.length)map.fitBounds(bounds,{padding:[24,24],maxZoom:14})}
function openMap(){if(!window.L)return toast('地図ライブラリを読み込めませんでした');E.mapModal.classList.add('show');E.mapModal.setAttribute('aria-hidden','false');E.mapTitle.textContent=`${region}・地図から選局`;if(!map){map=L.map('map').setView([35.0116,135.7681],12);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap'}).addTo(map);mapLayer=L.layerGroup().addTo(map)}setTimeout(()=>{map.invalidateSize();renderMapMarkers()},80)}
function closeMap(){E.mapModal.classList.remove('show');E.mapModal.setAttribute('aria-hidden','true')}
window.onYouTubeIframeAPIReady=()=>{if(!data.length)data=regionData(region);apiReady=true;slotMap=[0,Math.min(1,data.length-1),data.length-1];for(let s=0;s<3;s++){const v=data[slotMap[s]];players[s]=new YT.Player(`yt${s}`,{videoId:v.id,playerVars:{playsinline:1,rel:0,modestbranding:1,start:v.start||0},events:{onStateChange:e=>{const v2=data[slotMap[s]];if(s===activeSlot&&e.data===YT.PlayerState.ENDED&&autoNext&&v2&&!v2.live)switchTo(current+1,true,true)}}})}toast('プレイヤー準備完了')};
E.start.onclick=()=>{if(!apiReady)return toast('プレイヤー準備中です');started=true;E.boot.classList.add('hidden');if(scheduleMode)applySchedule(true);try{players[activeSlot].playVideo()}catch(e){}};
E.prev.onclick=()=>switchTo(current-1,true,true);E.next.onclick=()=>switchTo(current+1,true,true);E.mapBtn.onclick=openMap;E.mapClose.onclick=closeMap;E.mapModal.onclick=e=>{if(e.target===E.mapModal)closeMap()};E.yearAgo.onclick=jumpYearAgo;E.random.onclick=()=>{const list=data.filter(v=>matches(v,''));if(!list.length)return toast('該当チャンネルなし');let v=list[Math.floor(Math.random()*list.length)];tuneGlobal(v)};E.guideBtn.onclick=()=>{const h=E.guide.classList.toggle('hidden');E.layout.classList.toggle('full',h)};E.compareTop.onclick=()=>{const rel=nearby(data[current]);if(!rel.length)return toast('比較候補なし');tuneGlobal(data[current].live?(rel.find(v=>!v.live)||rel[0]):(rel.find(v=>v.live)||rel[0]))};E.search.oninput=renderChannels;E.auto.onclick=()=>{autoNext=!autoNext;E.auto.classList.toggle('on',autoNext)};E.scheduleBtn.onclick=()=>{scheduleMode=!scheduleMode;E.scheduleBtn.classList.toggle('on',scheduleMode);lastSchedule='';if(scheduleMode)applySchedule(true);renderChannels();renderSchedule()};E.liveOnly.onclick=()=>{cat=cat==='LIVE'?'すべて':'LIVE';area='すべて';season='すべて';E.liveOnly.classList.toggle('on',cat==='LIVE');tabs(E.tabs,cats(),'cat');tabs(E.regions,areas(),'area');tabs(E.seasons,seasonOrder,'season');renderChannels()};
setInterval(()=>{E.clock.textContent=hhmm(nowJST());applySchedule(false)},15000);
let sx=0,sy=0;E.stage.addEventListener('touchstart',e=>{const t=e.changedTouches[0];sx=t.clientX;sy=t.clientY},{passive:true});E.stage.addEventListener('touchend',e=>{const t=e.changedTouches[0],dx=t.clientX-sx,dy=t.clientY-sy;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.25)switchTo(current+(dx<0?1:-1),true,true)},{passive:true});
data=regionData(region);renderRegionSwitch();E.channelStat.textContent=`${data.length} CH ・ LIVE ${data.filter(v=>v.live).length}`;tabs(E.regions,areas(),'area');tabs(E.tabs,cats(),'cat');tabs(E.seasons,seasonOrder,'season');switchTo(0,false,false);E.clock.textContent=hhmm(nowJST());renderSchedule();
})();