window.KYOTO_CHANNELS=[
{num:517,name:'清水寺',id:'54xjOKO-4z4',title:'清水寺界隈を歩く',meta:'清水寺・三年坂',cat:'王道名所',area:'東山'},
{num:518,name:'祇園',id:'MXdMGi8DN3I',title:'夕暮れの祇園を歩く',meta:'祇園・八坂',cat:'夜の京都',area:'東山'},
{num:519,name:'伏見稲荷',id:'sNwYJG0g_oI',title:'伏見稲荷大社 4K Walking Tour',meta:'千本鳥居',cat:'王道名所',area:'伏見'},
{num:520,name:'早朝伏見',id:'pggb97tSmWU',title:'早朝の伏見稲荷・千本鳥居',meta:'早朝散歩',cat:'癒やし',area:'伏見'},
{num:521,name:'嵐山',id:'1La4QzGeaaQ',title:'京都・嵐山を歩く',meta:'竹林・渡月橋',cat:'自然・散策',area:'嵐山'},
{num:522,name:'京都駅',id:'S_hR7s66ccI',title:'京都駅周辺ウォーク',meta:'京都駅',cat:'街歩き',area:'中心部'},
{num:523,name:'祇園クイック',id:'hTzhPTQAbuw',title:'祇園 Walking Tour',meta:'祇園を短時間で散策',cat:'街歩き',area:'東山'},
{num:524,name:'祇園→清水寺',id:'-IIcL5u00uM',title:'祇園・清水エリア王道ルート',meta:'円山公園・ねねの道・二年坂・三年坂・清水寺',cat:'王道名所',area:'東山'},
{num:525,name:'哲学の道',id:'tEHxKJrH1fY',title:'哲学の道 Walking Tour',meta:'銀閣寺方面へ散策',cat:'自然・散策',area:'洛東'},
{num:526,name:'哲学の道 新緑',id:'MSU8tn1H1d0',title:'新緑の哲学の道 4K',meta:'約1.5kmの散策ルート',cat:'季節',area:'洛東'},
{num:527,name:'錦市場',id:'tU2R7JPdkCo',title:'錦市場 Walking Tour 4K',meta:'四条通から錦市場へ',cat:'グルメ',area:'中心部',chapters:[['イントロ',0],['地図',81],['四条通',98],['錦市場',420],['エンディング',1313]]},
{num:528,name:'三年坂・二年坂',id:'sIPxcCWTGGA',title:'東山 三年坂周辺を歩く 4K',meta:'ねねの道・二年坂・三年坂',cat:'街歩き',area:'東山',chapters:[['ねねの道',10],['維新の道',120],['二年坂',200],['三年坂',370],['清水坂',755]]},
{num:529,name:'ねねの道 春',id:'yi4CXHRWJsY',title:'ねねの道・二年坂・三年坂',meta:'春の東山・枝垂桜',cat:'季節',area:'東山'},
{num:530,name:'東寺',id:'Y5zLYdYMuU4',title:'京都 東寺を歩く 4K',meta:'羅生門跡・五重塔・東寺',cat:'王道名所',area:'洛南'},
{num:531,name:'金閣寺',id:'_t0obD-GH40',title:'金閣寺を歩く 4K',meta:'京都を代表する人気スポット',cat:'王道名所',area:'衣笠'},
{num:532,name:'貴船神社',id:'B-mpXfvnSLM',title:'貴船神社と川床を歩く 4K',meta:'夏の貴船・川床',cat:'自然・散策',area:'洛北'},
{num:533,name:'銀閣寺 秋',id:'D_61ENOndn8',title:'哲学の道から銀閣寺へ 4K',meta:'秋の銀閣寺・哲学の道',cat:'季節',area:'洛東',chapters:[['哲学の道',0],['銀閣寺参道',153],['銀閣寺',344]]},
{num:534,name:'高台寺 夜間拝観',id:'dfyy6cQZXoY',title:'高台寺 夏の特別夜間拝観 4K',meta:'東山・高台寺の夜',cat:'夜の京都',area:'東山'},
{num:535,name:'南禅寺 桜',id:'0otw_AhD6Yg',title:'満開の南禅寺を歩く 4K',meta:'2026年・桜満開の南禅寺',cat:'季節',area:'洛東'},
{num:536,name:'清水寺〜ねねの道',id:'dbxOoTyRtdc',title:'清水寺界隈を歩く 4K',meta:'清水寺・産寧坂・二年坂・ねねの道',cat:'街歩き',area:'東山',chapters:[['清水寺門前',0],['清水坂',73],['産寧坂',449],['八坂の塔',852],['二年坂',870],['ねねの道',1208]]},
{num:537,name:'四条河原町',id:'E_QVUN-HbW8',title:'大晦日の四条河原町を歩く 4K',meta:'新京極・寺町京極・四条河原町',cat:'街歩き',area:'中心部',chapters:[['四条河原町',0],['新京極',206],['蛸薬師堂',490],['ろっくんプラザ',700],['寺町京極',1056]]},
{num:538,name:'雪の嵐山',id:'XK67aSkI4pk',title:'小雪が降る嵐山を散策 4K',meta:'渡月橋・保津川・亀山公園',cat:'季節',area:'嵐山'},
{num:539,name:'雪の竹林・渡月橋',id:'MFZGRdr2NwI',title:'雪の降る京都嵐山を歩く 4K',meta:'渡月橋・竹林の小径・野宮神社',cat:'季節',area:'嵐山'},
{num:540,name:'雪の清水寺',id:'J6ZdVdoHo3A',title:'夕暮れの雪景色・清水寺',meta:'2026年冬・雪化粧した清水寺',cat:'季節',area:'東山'},
{num:541,name:'冬の祇園',id:'KmWXXfDbPu8',title:'冬の穏やかな祇園を歩く 4K',meta:'花見小路・巽橋・祇園白川',cat:'街歩き',area:'東山'},
{num:601,name:'竹林の小径 LIVE',id:'Op-lf2NRMzs',title:'嵯峨嵐山 竹林の小径 ライブカメラ',meta:'京都市観光協会公式・リアルタイム',cat:'LIVE',area:'嵐山',live:true},
{num:602,name:'花見小路 LIVE',id:'X5rq4ioggLk',title:'花見小路 ライブカメラ',meta:'京都市観光協会公式・リアルタイム',cat:'LIVE',area:'東山',live:true},
{num:603,name:'伏見稲荷 LIVE',id:'Onyb8uHQV5Y',title:'伏見稲荷大社付近 裏参道ライブ',meta:'京都市観光協会公式・リアルタイム',cat:'LIVE',area:'伏見',live:true},
{num:604,name:'哲学の道 LIVE',id:'S6IkZhhwG4A',title:'哲学の道 ライブカメラ',meta:'京都市観光協会公式・リアルタイム',cat:'LIVE',area:'洛東',live:true},
{num:605,name:'大覚寺 LIVE',id:'ldO0Eqoomms',title:'大覚寺 ライブカメラ',meta:'京都市観光協会公式・リアルタイム',cat:'LIVE',area:'嵐山',live:true}
];